### ISSUE TITLE
Woocommerce Views not recognized on Publish

### ISSUE THREAD

**Issue by Salemoche** [generoi/sage-woocommerce#15] opened 2022-03-31 11:03 UTC
I have just published my site from my local development server to [live](https://dev.vigia.tech/). Following the [FTP Build Instructions](https://docs.roots.io/sage/10.x/deployment/#deploying-sage-via-ftp) of the Sage documentation to publish my Site via FTP worked well but any Woocommerce related Sites (e.g. [shop](https://dev.vigia.tech/shop/) ) won't use the blade templates.
For reference a screenshot from my local setup:

<img width="1775" alt="Screenshot 2022-03-31 at 13 00 14" src="https://user-images.githubusercontent.com/15328313/161040916-93b18899-2c6e-4e7f-b388-1f91dfd5da2f.png">

Am I missing a step?

**Comment by saltlucas** [comment] 2022-11-11 05:46
@Salemoche I am having the same issue.  Did you figure it out?

**Comment by Salemoche** [comment] 2022-11-11 08:44
@saltlucas I did not, I ended up just rewriting the affected components in plain PHP since Time was critical. I have since moved away from sage in general

**Comment by oxyc** [comment] 2022-11-11 19:20
do you have any other sage packages in use that work? it sounds like the service provider isnt loaded which would indicate maybe you didn’t run `composer dump-autoloader` and commit it?

**Comment by saltlucas** [comment] 2022-11-11 21:43
Thanks, I tried the `composer dump-autoload` command with no luck.

I confirmed the service provider is being loaded.

The issue seems to be that the cache:
-  views
- packages.php
- services.php 

in `cache/acorn/framework` are not being updated with generoi/sage-woocommerce properly.  Other service providers are writing to views and updated those files correctly.  I don’t see any write errors at the moment.

 If I manually copy them from the local site cache the views will load correctly.

I am on Pantheon btw so it could be unique to their environment. I will debug further.

**Comment by saltlucas** [comment] 2022-11-11 22:11
Also, after debugging I don't think this is necessarily related to your package.  There are similar issues reported [here](https://discourse.roots.io/t/packages-in-sage-10-not-working-on-deployment/23792) for example.

**Comment by oxyc** [comment] 2022-11-11 23:37
Is the cache cache folder writable (eg configured to be in uploads folder?) This package generates the views dynamically,`wp acorn view:cache` doesnt generate them.

**Comment by oxyc** [comment] 2022-11-11 23:48
If you can send over a zip file I can have a look too. More eyes is always better :)

**Comment by saltlucas** [comment] 2022-11-14 17:56
@oxyc Yes, it is writeable.  If I delete the cache manually it rewrites fine.  So I think the issue is just that when the view changed on a new push to the server the cache didn't change.  I will have to look more into later.

**Comment by oxyc** [comment] 2023-04-26 15:02
Going to close this, do let me know if there's anything I can help with

**Closed by oxyc** 2023-04-26 15:02 UTC
