### ISSUE TITLE
Issue with acorn view:cache and WP Engine

### ISSUE THREAD

**Issue by svenkaptein** [generoi/sage-woocommerce#33] opened 2024-05-30 13:20 UTC
We use sage roots 10 on WP Engine with your library.
The loader files are now created in the view cache folder when the page is visited and not when wp acorn view:cache command is ran. This is an issue on WP Engine, because you need to be logged in, in order to create php files on the filesystem.

Is it possible that those loader files are created when running wp acorn view:cache? 

Also see this thread on discourse: https://discourse.roots.io/t/what-are-loaders-view-makeloader-and-why-are-they-needed/26992

**Comment by oxyc** [comment] 2024-06-06 17:28
The issue is that some functions/filters (eg `wc_get_template()`) expects a filesystem path which they will `include`.
If we passed the compiled view directly eg. View Composers would not run 

Looking at [`wc_get_template()`](https://github.com/woocommerce/woocommerce/blob/26158ee6b493045cf012dd65239cffce029e3666/plugins/woocommerce/includes/wc-core-functions.php#L313-L347) again, I don't see any way to extract the composer provided variables. We would need a way to filter the `$args` which there isn't.

I'm happy to support it if someone comes up with a way to make it work :)

**Comment by oxyc** [comment] 2024-06-06 17:47
Now that I think about it, the way you said might actually work.

We could make a custom console command that runs `view($template)->makeLoader()` on all templates in `resources/views/woocommerce/` acorn [should use it](https://github.com/roots/acorn/blob/67091c0bdced0ca08abe6ee1e1fa56538c85e69c/src/Roots/Acorn/View/ViewServiceProvider.php#L120) if it already exists. Some unused files would be created but that's not really an issue.

Pretty busy with work and life so not sure when I have time to look into it, happy to accept PRs for a custom console command or one that hooks into the `view:cache` task.

**Comment by oxyc** [comment] 2024-06-06 18:37
Quick and dirty but might work? https://gist.github.com/oxyc/151f9fb7579a1c51e8049fe507176218

Should work with any acorn loader I guess? Would need to run _after_ `view:cache` since that one clears compiled views. `viewloader:cache`

**Comment by svenkaptein** [comment] 2024-06-07 12:23
@oxyc I would say this approach should work, but I have no idea how to test your code. I just include your library and followed the documentation :) So if you tell me where to place it / test it I can do it :)

**Comment by oxyc** [comment] 2024-06-07 13:14
if you use sage theme you can create `app/Console/ViewLoaderCacheCommand.php` with the contents of that gist.

Then add it to your `ThemeServiceProvider.php`:

```php
public function boot()
{
    $this->commands([
        \App\Console\ViewLoaderCacheCommand::class,
    ]);
    parent::boot();
}
```

Now `wp acorn viewloader:cache` should be available

**Comment by oxyc** [comment] 2024-06-07 13:16
I can see us using it for sites too so if it works I might create a package at some point and then you can composer require it. Or if you do, let me know so I can use it :)

**Comment by svenkaptein** [comment] 2024-06-07 14:18
Thanks! I got this integrated in my sage theme and indeed creates all the loader files.
Now the only problem is that when visiting the page it does not detect the loader file is there and tries to create a different one (with a different filename), which is blocked at WP Engine.

So it seems it does not know how to locate the loader file... Any clue?

Here some debug log from WP Engine:
```
[2024-06-07T14:05:39.262432+00:00] PHP Warning:  file_put_contents(/nas/content/live/pdv/wp-content/cache/acorn/framework/views/621dab58f2036ec93093554c7b004a8c-loader.php): Failed to open stream: Permission denied in /nas/content/live/pdv/wp-content/themes/bra/vendor/roots/acorn/src/Roots/Acorn/View/ViewServiceProvider.php on line 120
[2024-06-07T14:05:39.262533+00:00] PHP Warning:  require(/nas/content/live/pdv/wp-content/cache/acorn/framework/views/621dab58f2036ec93093554c7b004a8c-loader.php): Failed to open stream: No such file or directory in /nas/content/live/pdv/wp-includes/template.php on line 812
[2024-06-07T14:05:39.262798+00:00] PHP Fatal error:  Uncaught Error: Failed opening required '/nas/content/live/pdv/wp-content/cache/acorn/framework/views/621dab58f2036ec93093554c7b004a8c-loader.php' (include_path='.:/usr/share/pear/php:/usr/share/php') in /nas/content/live/pdv/wp-includes/template.php:812#012Stack trace:#012#0 /nas/content/live/pdv/wp-content/plugins/woocommerce/includes/wc-core-functions.php(284): load_template('/nas/content/li...', false)#012#1 /nas/content/live/pdv/wp-content/cache/acorn/framework/views/3891cee8ad11601a82e6df8177a2e82cde085c57.php(364): wc_get_template_part('content', 'single-product')#012#2 /nas/content/live/pdv/wp-content/themes/bra/vendor/illuminate/filesystem/Filesystem.php(109): require('/nas/content/li...')#012#3 /nas/content/live/pdv/wp-content/themes/bra/vendor/illuminate/filesystem/Filesystem.php(110): Illuminate\Filesystem\Filesystem::Illuminate\Filesystem\{closure}()#012#4 /nas/content/live/pdv/wp-content/themes/bra/vendor/illuminate/view/Engines/PhpEngine.php(58): Illuminate\Filesystem\Filesystem->getRequire('/nas/content/li...', Array)#012#5 /nas/content/live/pdv/wp-content/themes/bra/vendor/illuminate/view/Engines/CompilerEngine.php(70): Illuminate\View\Engines\PhpEngine->evaluatePath('/nas/content/li...', Array)#012#6 /nas/content/live/pdv/wp-content/themes/bra/vendor/illuminate/view/View.php(195): Illuminate\View\Engines\CompilerEngine->get('/nas/content/li...', Array)#012#7 /nas/content/live/pdv/wp-content/themes/bra/vendor/illuminate/view/View.php(178): Illuminate\View\View->getContents()#012#8 /nas/content/live/pdv/wp-content/themes/bra/vendor/illuminate/view/View.php(147): Illuminate\View\View->renderContents()#012#9 /nas/content/live/pdv/wp-content/themes/bra/index.php(35): Illuminate\View\View->render()#012#10 /nas/content/live/pdv/wp-includes/template-loader.php(106): include('/nas/content/li...')#012#11 /nas/content/live/pdv/wp-blog-header.php(19): require_once('/nas/content/li...')#012#12 /nas/content/live/pdv/index.php(17): require('/nas/content/li...')#012#13 {main}#012#012Next Illuminate\View\ViewException: Failed opening required '/nas/content/live/pdv/wp-content/cache/acorn/framework/views/621dab58f2036ec93093554c7b004a8c-loader.php' (include_path='.:/usr/share/pear/php:/usr/share/php') (View: /nas/content/live/pdv/wp-content/themes/bra/resources/views/woocommerce/single-product.blade.php) in /nas/content/live/pdv/wp-includes/template.php:812#012Stack trace:#012#0 /nas/content/live/pdv/wp-content/themes/bra/vendor/illuminate/view/Engines/PhpEngine.php(60): Illuminate\View\Engines\CompilerEngine->handleViewException(Object(Error), 4)#012#1 /nas/content/live/pdv/wp-content/themes/bra/vendor/illuminate/view/Engines/CompilerEngine.php(70): Illuminate\View\Engines\PhpEngine->evaluatePath('/nas/content/li...', Array)#012#2 /nas/content/live/pdv/wp-content/themes/bra/vendor/illuminate/view/View.php(195): Illuminate\View\Engines\CompilerEngine->get('/nas/content/li...', Array)#012#3 /nas/content/live/pdv/wp-content/themes/bra/vendor/illuminate/view/View.php(178): Illuminate\View\View->getContents()#012#4 /nas/content/live/pdv/wp-content/themes/bra/vendor/illuminate/view/View.php(147): Illuminate\View\View->renderContents()#012#5 /nas/content/live/pdv/wp-content/themes/bra/index.php(35): Illuminate\View\View->render()#012#6 /nas/content/live/pdv/wp-includes/template-loader.php(106): include('/nas/content/li...')#012#7 /nas/content/live/pdv/wp-blog-header.php(19): require_once('/nas/content/li...')#012#8 /nas/content/live/pdv/index.php(17): require('/nas/content/li...')#012#9 {main}#012  thrown in /nas/content/live/pdv/wp-includes/template.php on line 812
```

So this file '621dab58f2036ec93093554c7b004a8c-loader.php' it tries to create already exist with excact that same content as file 'b21f1116cd05311b1067e7374556fd4e-loader.php' which was created by your new console command.

**Comment by oxyc** [comment] 2024-06-07 16:10
Ah it uses absolute paths :/ 

Acorn might be up for using relative paths in the id instead https://gist.github.com/oxyc/fdbdc4766a23bc691aa9eb03e9445a4c to support having the loaders pre-compiled. You can always ask them if they would be open to changing it.

If not, it should be fixable by adding this to that same `boot()` function to override Acorns macro and use relative paths instead of absolute when generating the id

```php
        $app = $this->app;

        \Illuminate\View\View::macro('getCompiled', function () use ($app) {
            /** @var string $file path to file */
            $file = $this->getPath();

            /** @var Engine $engine */
            $engine = $this->getEngine();

            $path = ($engine instanceof \Illuminate\View\Engines\CompilerEngine)
                ? $engine->getCompiler()->getCompiledPath($file)
                : $file;


            $compiledPath = $app['config']['view.compiled'];
            return \Illuminate\Support\Str::after($path, $compiledPath);
        });
```

**Comment by svenkaptein** [comment] 2024-06-09 11:51
Perfect, looks like it works like a charm!

**Comment by oxyc** [comment] 2024-06-09 15:58
Thanks for testing, I made it into a composer package, do you mind testing if it works as well?https://github.com/generoi/sage-cacheable-viewloaders

**Comment by svenkaptein** [comment] 2024-06-11 07:36
@oxyc this package seems to have the same path issue you fixed in the theme solution:
```
2024-06-11T07:33:46.403362+00:00] PHP Warning:  file_put_contents(/nas/content/live/pdv/wp-content/cache/acorn/framework/views/621dab58f2036ec93093554c7b004a8c-loader.php): Failed to open stream: Permission denied in /nas/content/live/pdv/wp-content/themes/bra/vendor/roots/acorn/src/Roots/Acorn/View/ViewServiceProvider.php on line 120
[2024-06-11T07:33:46.403461+00:00] PHP Warning:  require(/nas/content/live/pdv/wp-content/cache/acorn/framework/views/621dab58f2036ec93093554c7b004a8c-loader.php): Failed to open stream: No such file or directory in /nas/content/live/pdv/wp-includes/template.php on line 812
[2024-06-11T07:33:46.404410+00:00] PHP Fatal error:  Uncaught Error: Failed opening required '/nas/content/live/pdv/wp-content/cache/acorn/framework/views/621dab58f2036ec93093554c7b004a8c-loader.php' (include_path='.:/usr/share/pear/php:/usr/share/php') in /nas/content/live/pdv/wp-includes/template.php:812#012Stack trace:#012#0 /nas/content/live/pdv/wp-content/plugins/woocommerce/includes/wc-core-functions.php(284): load_template('/nas/content/li...', false)#012#1 /nas/content/live/pdv/wp-content/cache/acorn/framework/views/3891cee8ad11601a82e6df8177a2e82cde085c57.php(364): wc_get_template_part('content', 'single-product')#012#2 /nas/content/live/pdv/wp-content/themes/bra/vendor/illuminate/filesystem/Filesystem.php(109): require('/nas/content/li...')#012#3 /nas/content/live/pdv/wp-content/themes/bra/vendor/illuminate/filesystem/Filesystem.php(110): Illuminate\Filesystem\Filesystem::Illuminate\Filesystem\{closure}()#012#4 /nas/content/live/pdv/wp-content/themes/bra/vendor/illuminate/view/Engines/PhpEngine.php(58): Illuminate\Filesystem\Filesystem->getRequire('/nas/content/li...', Array)#012#5 /nas/content/live/pdv/wp-content/themes/bra/vendor/illuminate/view/Engines/CompilerEngine.php(70): Illuminate\View\Engines\PhpEngine->evaluatePath('/nas/content/li...', Array)#012#6 /nas/content/live/pdv/wp-content/themes/bra/vendor/illuminate/view/View.php(195): Illuminate\View\Engines\CompilerEngine->get('/nas/content/li...', Array)#012#7 /nas/content/live/pdv/wp-content/themes/bra/vendor/illuminate/view/View.php(178): Illuminate\View\View->getContents()#012#8 /nas/content/live/pdv/wp-content/themes/bra/vendor/illuminate/view/View.php(147): Illuminate\View\View->renderContents()#012#9 /nas/content/live/pdv/wp-content/themes/bra/index.php(35): Illuminate\View\View->render()#012#10 /nas/content/live/pdv/wp-includes/template-loader.php(106): include('/nas/content/li...')#012#11 /nas/content/live/pdv/wp-blog-header.php(19): require_once('/nas/content/li...')#012#12 /nas/content/live/pdv/index.php(17): require('/nas/content/li...')#012#13 {main}#012#012Next Illuminate\View\ViewException: Failed opening required '/nas/content/live/pdv/wp-content/cache/acorn/framework/views/621dab58f2036ec93093554c7b004a8c-loader.php' (include_path='.:/usr/share/pear/php:/usr/share/php') (View: /nas/content/live/pdv/wp-content/themes/bra/resources/views/woocommerce/single-product.blade.php) in /nas/content/live/pdv/wp-includes/template.php:812#012Stack trace:#012#0 /nas/content/live/pdv/wp-content/themes/bra/vendor/illuminate/view/Engines/PhpEngine.php(60): Illuminate\View\Engines\CompilerEngine->handleViewException(Object(Error), 4)#012#1 /nas/content/live/pdv/wp-content/themes/bra/vendor/illuminate/view/Engines/CompilerEngine.php(70): Illuminate\View\Engines\PhpEngine->evaluatePath('/nas/content/li...', Array)#012#2 /nas/content/live/pdv/wp-content/themes/bra/vendor/illuminate/view/View.php(195): Illuminate\View\Engines\CompilerEngine->get('/nas/content/li...', Array)#012#3 /nas/content/live/pdv/wp-content/themes/bra/vendor/illuminate/view/View.php(178): Illuminate\View\View->getContents()#012#4 /nas/content/live/pdv/wp-content/themes/bra/vendor/illuminate/view/View.php(147): Illuminate\View\View->renderContents()#012#5 /nas/content/live/pdv/wp-content/themes/bra/index.php(35): Illuminate\View\View->render()#012#6 /nas/content/live/pdv/wp-includes/template-loader.php(106): include('/nas/content/li...')#012#7 /nas/content/live/pdv/wp-blog-header.php(19): require_once('/nas/content/li...')#012#8 /nas/content/live/pdv/index.php(17): require('/nas/content/li...')#012#9 {main}#012  thrown in /nas/content/live/pdv/wp-includes/template.php on line 812
```

**Comment by oxyc** [comment] 2024-06-12 20:57
Doh... I had a typo, hopefully works in https://github.com/generoi/sage-cacheable-viewloaders/releases/tag/v0.1.1

**Comment by oxyc** [comment] 2024-06-20 23:54
ill close this one and will refer people to the separate package instead.

**Closed as not planned by oxyc** 2024-06-20 23:54 UTC
